Appraisal/urls.py
from django.urls import path
from Appraisal import views

urlpatterns = [
    path('getappraisal',views.getAppraisal,name='getappraisal' ),
    path('getemployeeappaisal',views.getEmployeeAppraisal,name='getemployeeappaisal'),
    path('appraisaldetail',views.appraisaldetail,name='appraisaldetail'),
    path('',views.index,name='home')
]

Employee_Apprasial/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Appraisal.urls'))
]

Appraisal/models.py
from django.db import models
from Department.models import Department

# Create your models here.

class Appraisal(models.Model):
    appraisal_ID = models.AutoField(primary_key=True)
    objective = models.CharField(max_length=40,verbose_name='objective')
    year = models.CharField(max_length=4,verbose_name='year')
    department_ID = models.ForeignKey(Department,on_delete=models.CASCADE)
    employee_ID = models.ForeignKey("Employee.Employee",on_delete=models.CASCADE)
    rating = models.IntegerField()

    def __str__(self):
        return (str(self.appraisal_ID))+" - "+(self.year)

    class Meta:
        verbose_name = 'Appraisal'
        verbose_name_plural = 'Appraisals'

class manager(models.Model):
    manager_ID = models.AutoField(primary_key=True)
    manager_name=models.CharField(max_length=30,verbose_name='manager name')

    def __str__(self):
        return (str(self.manager_ID))+" - "+self.manager_name

    class Meta:
        verbose_name='manager'
        verbose_name_plural='managers'





Department/models.py
from django.db import models

# Create your models here.

class Department(models.Model):
    department_ID=models.AutoField(primary_key=True)
    department_name=models.CharField(max_length=30,verbose_name='department name')

    def __str__(self):
        return (str(self.department_ID))+" - "+(self.department_name)

    class Meta:
        verbose_name='Department'
        verbose_name_plural='Departments'

Employee/models.py
from django.db import models
from Department.models import Department
from Jobs.models import Jobs
# Create your models here.

class Employee(models.Model):
    employee_ID = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=15,verbose_name='first name')
    last_name = models.CharField(max_length=15,verbose_name='last name')
    email = models.CharField(max_length=30,verbose_name='email')
    contact = models.CharField(max_length=20,verbose_name='contact')
    adress = models.TextField()
    manager_ID = models.ForeignKey("Appraisal.manager",on_delete=models.CASCADE)
    job_ID = models.ForeignKey(Jobs,on_delete=models.CASCADE)
    department_ID = models.ForeignKey(Department,on_delete=models.CASCADE)
    hire_date=models.DateField(verbose_name='hire date')
    is_activte=models.BooleanField(verbose_name='is active',default=True)

    def __str__(self):
        return (str(self.employee_ID))+'  -  '+(self.first_name+' '+self.last_name)

    class Meta:
        verbose_name='Employee'
        verbose_name_plural='Employees'

Jobs/models.py
from django.db import models

# Create your models here.

class Jobs(models.Model):
    job_ID=models.AutoField(primary_key=True)
    job_title=models.CharField(max_length=20,verbose_name='Job Title')

    def __str__(self):
        return (str(self.job_ID))+"  -   "+(self.job_title)

    class Meta:
        verbose_name='Job'
        verbose_name_plural='Jobs'

Appraisal/views.py
from django.shortcuts import render,redirect
from django.http.response import JsonResponse
from rest_framework.parsers import JSONParser
# Create your views here.
from .form import EmpForm
from rest_framework.decorators import api_view
from .serializers import AppraisalSerializer
from .models import Appraisal,manager
from Employee.models import Employee


@api_view(['GET', 'POST', 'DELETE'])
def getAppraisal(request):
    if request.method == 'POST':
        data=request.POST
        employe=Employee.objects.filter(manager_ID=data['manager_id'])
        appraisal=Appraisal.objects.filter(employee_ID__in=employe)
        data=[]
        for item in appraisal:
            temp={}
            temp['appraisal_id']=item.appraisal_ID
            temp['objective']=item.objective
            temp['year']=item.year
            temp['department_name']=item.department_ID.department_name
            temp['employee_name']=item.employee_ID.first_name+" "+item.employee_ID.last_name
            temp['rating']=item.rating
            data.append(temp)
        return JsonResponse(data,safe=False)


@api_view(['GET', 'POST', 'DELETE'])
def getEmployeeAppraisal(request):
    if request.method == 'POST':
        data=request.POST
        appraisal=Appraisal.objects.filter(employee_ID=data['employee_id'])
        data=[]
        for item in appraisal:
            temp={}
            temp['appraisal_id']=item.appraisal_ID
            temp['objective']=item.objective
            temp['year']=item.year
            temp['department_name']=item.department_ID.department_name
            temp['employee_name']=item.employee_ID.first_name+" "+item.employee_ID.last_name
            temp['rating']=item.rating
            data.append(temp)
        return JsonResponse(data,safe=False)

def appraisaldetail(request,id=None):
    appraisal=None

    if request.method=="POST":
        appraisalform=EmpForm(request.POST,instance=appraisal)
        if appraisalform.is_valid():
            data=request.POST
            appr=Appraisal.objects.filter(appraisal_ID=request.session.get('appraisalid')).update(
                objective=data['objective'],
                year=data['year'],
                department_ID=data['department_ID'],
                rating=data['rating']
            )
            return redirect('/appraisaldetail?id='+request.session.get('appraisalid'))
    if request.GET.get('appraisalid', ''):
        request.session['appraisalid']=request.GET.get('appraisalid', '')

        apprid=request.GET.get('appraisalid', '')
        appraisal = Appraisal.objects.get(appraisal_ID=apprid)
        appraisalform=EmpForm(instance=appraisal)
        return render(request,'editappraisal.html',{'form':appraisalform})

    id = request.GET.get('id', '')
    appraisal = Appraisal.objects.get(appraisal_ID=id)
    temp = {}
    temp['appraisal_id'] = appraisal.appraisal_ID
    temp['objective'] = appraisal.objective
    temp['year'] = appraisal.year
    temp['department_name'] = appraisal.department_ID.department_name
    temp['employee_name'] = appraisal.employee_ID.first_name + " " + appraisal.employee_ID.last_name
    temp['rating'] = appraisal.rating
    context=temp
    return render(request,'appraisaldetail.html',context)





def index(request):
    return render(request,'index.html')

Department/views.py
from django.shortcuts import render

# Create your views here.

Employee/views.py
from django.shortcuts import render

# Create your views here.

Jobs/views.py
from django.shortcuts import render

# Create your views here.

Appraisal/templates/appraisaldetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .card {
  /* Add shadows to create the "card" effect */
  height: 1000px;
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  transition: 0.3s;
}

/* On mouse-over, add a deeper shadow */
.card:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

/* Add some padding inside the card container */
.container {
  padding: 2px 16px;
}

p{
    font-size: 16px;
    margin-left: 20px;
    margin-top: 20px;
    font-weight: 500;
}
.dtlbtn{
      width: 70px;
  background-color: #4CAF50;
  height: 100px;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}
.item{
    display: flex;
    justify-content: start;
}
h4{
    text-align: left;
}
    </style>
</head>
<body>
<div class="card_wraper">

    <center><h3>Employee Appraisal Detail</h3></center>
<div class="card">

  <div class="container">
    <div class="item"><h4>Employee Name: </h4><p>{{ employee_name}}</p></div>
      <div class="item"><h4>Department Name: </h4> <p>{{ department_name}}</p></div>
    <div class="item"><h4>Objective:</h4><p>{{ objective}}</p></div>
     <div class="item"> <h4>Year: </h4><p>{{ year}}</p></div>
    <div class="item"><h4>Rating: </h4><p>{{ rating}}</p></div>
  </div>
    <a href="/appraisaldetail?appraisalid={{ appraisal_id }}" class="dtlbtn">Edit</a>
</div>

    </div>


</body>
</html>

Appraisal/templates/editappraisal.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Title</title>
    <style>
        input[type="text"]{
            margin-left: 40px;
        }
        #id_year{
            margin-left: 77px;
        }
        label{
            margin-left: 10px;
            font-weight: 600;
        }
        #id_employee_ID{
            margin-left: 17px;
        }
        #id_rating{
            margin-left: 65px;
        }
        .savebtn{
            margin-left: 30px;
        }
        form{
            margin-top: 20px;
        }
    </style>
</head>
<body>
<center><h4>Edit Employee Appraisal</h4></center>
<form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="savebtn">Save</button>
    </form>
</body>
</html>

Appraisal/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style>

        .tab {
  display: flex;
  justify-content: space-evenly;
  overflow: hidden;
  border: 1px solid #ccc;
  background-color: #f1f1f1;
}

/* Style the buttons that are used to open the tab content */
.tab button {
  background-color: inherit;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  transition: 0.3s;
}

/* Change background color of buttons on hover */
.tab button:hover {
  background-color: #ddd;
}

/* Create an active/current tablink class */
.tab button.active {
  background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
  display: none;
  padding: 6px 12px;
  border: 1px solid #ccc;
  border-top: none;
}

.tabcontent {
  animation: fadeEffect 1s; /* Fading effect takes 1 second */
}

/* Go from zero to full opacity */
@keyframes fadeEffect {
  from {opacity: 0;}
  to {opacity: 1;}
}

.vl {
  border-left: 6px solid black;
}

input[type=text], select {
  width: 30%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

.btn {
  width: 30%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

#employee_id {
    margin-left: 50%;
}

#employebtn{
         margin-left: 50%;
 }

.card {
  /* Add shadows to create the "card" effect */
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  height: 200px;
  transition: 0.3s;

}

/* On mouse-over, add a deeper shadow */
.card:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

/* Add some padding inside the card container */
.container {
  padding: 2px 16px;
}

.dtlbtn{
      width: 70px;
  background-color: #4CAF50;
  height: 100px;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

    </style>


</head>
<body>


<div class="tab">
  <button class="tablinks" onclick="openCity(event, 'London')" id="defaultOpen">Enter as manager</button>
    <div class="vl"></div>
  <button class="tablinks" onclick="openCity(event, 'Paris')">Enter as Employee</button>
</div>

<!-- Tab content -->
<div id="London" class="tabcontent">
<form id="managerdata" method="post">
            {% csrf_token %}
    <input type="text" id="manager_id" name="manager_id" placeholder="manager ID"><br>
    <button class="btn" id="managerbtn">Submit</button>
    </form>
</div>

<div id="Paris" class="tabcontent">
    <form id="employeedata" method="post">
            {% csrf_token %}
    <input type="text" id="employee_id" name="employee_id" placeholder="Employee ID"><br>
    <button class="btn" id="employebtn">Submit</button>
        </form>
</div>

<div id="card_wraper">

</div>


</body>

<script>

    $("#card_wraper").hide();
    function openCity(evt, cityName) {
  // Declare all variables
        $("#card_wraper").empty();
  var i, tabcontent, tablinks;

  // Get all elements with class="tabcontent" and hide them
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }

  // Get all elements with class="tablinks" and remove the class "active"
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }

  // Show the current tab, and add an "active" class to the button that opened the tab
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}


</script>

<script>
// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>

<script>

    $("form#managerdata").submit(function (e){
        e.preventDefault();
        var formData = new FormData(this);
            $.ajax({
        url:"{% url 'getappraisal' %}",
        type: 'POST',
        data: formData,
        success: function (data) {
            console.log(data);
            var card_wraper=$("#card_wraper")
            card_wraper.empty();
           for (var i = 0; i < data.length; i++) {

               var carditem="<div class='card'>"+"<div class='container'>"+"<h4><b>Employee Name: </b>"+ data[i].employee_name+"</h4>"+
                   "<h4><b>Department Name: </b>"+data[i].department_name+"</h4>"+"<h4><b>Rating: </b>"+data[i].rating+"</h4>"+"</div>"+
                   "<a href="+'/appraisaldetail?id='+data[i].appraisal_id+" class='dtlbtn'>"+"See Detail</a>"
                   "</div>"
            card_wraper.append(carditem)
           }
           card_wraper.show();

        },
        cache: false,
        contentType: false,
        processData: false
    });
    });


     $("form#employeedata").submit(function (e){
        e.preventDefault();
        var formData = new FormData(this);
            $.ajax({
        url:"{% url 'getemployeeappaisal' %}",
        type: 'POST',
        data: formData,
        success: function (data) {
            console.log(data);
            var card_wraper=$("#card_wraper")
            card_wraper.empty();
           for (var i = 0; i < data.length; i++) {

               var carditem="<div class='card'>"+"<div class='container'>"+"<h4><b>Employee Name: </b>"+ data[i].employee_name+"</h4>"+
                   "<h4><b>Department Name: </b>"+data[i].department_name+"</h4>"+"<h4><b>Rating: </b>"+data[i].rating+"</h4>"+
                   "<h4><b>Year: </b>"+data[i].year+"</h4>"+"<h4><b>Objective: </b>"+data[i].objective+"</h4>"
                   "</div>"+

                   "</div>"
                   card_wraper.append(carditem)
           }
           card_wraper.show();

        },
        cache: false,
        contentType: false,
        processData: false
    });
    });




</script>

</html>